name: 'Nextcloud App Version Management'
description: 'Manages version for Nextcloud apps'
outputs:
  new_version:
    description: 'The new version number'
runs:
  using: "composite"
  steps:
    - name: Get current version and increment
      id: increment_version
      shell: bash
      run: |
        current_version=$(grep -oP '(?<=<version>)[^<]+' appinfo/info.xml)
        IFS='.' read -ra version_parts <<< "$current_version"
        ((version_parts[2]++))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV
        echo "new_version=$new_version" >> $GITHUB_OUTPUT

    - name: Update version in info.xml
      shell: bash
      run: |
        sed -i "s|<version>.*</version>|<version>${{ env.NEW_VERSION }}</version>|" appinfo/info.xml

    - name: Commit version update
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump version to ${{ env.NEW_VERSION }}"
        git push
