name: 'Nextcloud App Build'
description: 'Builds the Nextcloud app'
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: zip, gd

    - name: Install npm dependencies
      shell: bash
      run: npm ci

    - name: Build npm
      shell: bash
      run: npm run build

    - name: Install Composer dependencies
      shell: bash
      run: composer install --no-dev
