name: 'Nextcloud App Store Upload'
description: 'Uploads the Nextcloud app to the App Store'
inputs:
  app_name:
    description: 'Name of the Nextcloud app'
    required: true
  appstore_token:
    description: 'Nextcloud App Store token'
    required: true
  version:
    description: 'Version to upload'
    required: true
runs:
  using: "composite"
  steps:
    - name: Upload app to Nextcloud appstore
      uses: nextcloud-releases/nextcloud-appstore-push-action@v1
      with:
        app_name: ${{ inputs.app_name }}
        appstore_token: ${{ inputs.appstore_token }}
        download_url: https://github.com/${{ github.repository }}/releases/download/v${{ inputs.version }}/${{ inputs.app_name }}-${{ inputs.version }}.tar.gz
        app_private_key: ${{ inputs.signing_key }}
        nightly: false
