name: 'Nextcloud App Release Action'
description: 'Automates the release process for Nextcloud apps'
inputs:
  app_name:
    description: 'Name of the Nextcloud app'
    required: true
  signing_cert:
    description: 'Signing certificate'
    required: true
  signing_key:
    description: 'Signing key'
    required: true
  appstore_token:
    description: 'Nextcloud App Store token'
    required: true
  github_token:
    description: 'GitHub token for creating releases'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Version Management
      uses: your-org/nextcloud-app-version-action@v1
      id: version

    - name: Build
      uses: your-org/nextcloud-app-build-action@v1

    - name: Package
      uses: your-org/nextcloud-app-package-action@v1
      with:
        app_name: ${{ inputs.app_name }}

    - name: Sign
      uses: your-org/nextcloud-app-sign-action@v1
      with:
        signing_cert: ${{ inputs.signing_cert }}
        signing_key: ${{ inputs.signing_key }}

    - name: Release
      uses: your-org/nextcloud-app-release-action@v1
      with:
        github_token: ${{ inputs.github_token }}
        version: ${{ steps.version.outputs.new_version }}
        app_name: ${{ inputs.app_name }}

    - name: App Store Upload
      uses: your-org/nextcloud-app-store-upload-action@v1
      with:
        app_name: ${{ inputs.app_name }}
        appstore_token: ${{ inputs.appstore_token }}
        version: ${{ steps.version.outputs.new_version }}
